version: "3"
services:
  app:
    image: nocobase/nocobase:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      - LOCAL_STORAGE_BASE_URL=${DOMAIN}
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=${ADMIN_PASSWORD}
      - INIT_ROOT_EMAIL=${ADMIN_EMAIL}
      - INIT_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - INIT_ROOT_NICKNAME=Super Admin
    volumes:
      - ./nocobase:/app/nocobase/storage
    ports:
      - "172.17.0.1:13000:80"

  postgres:
    image: postgres:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      POSTGRES_DB: nocobase
      POSTGRES_USER: nocobase
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data